import { Antonio } from "next/font/google";
import "./globals.css";
import Sessionprovider from "@/helpers/sessionProvider";

const ant = Antonio({ subsets: ["latin"] });

export const metadata = {
  title: "Big Brain 🧠",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ant.className} tracking-wide overflow-x-hidden dark`}>
        <Sessionprovider>
          {children}
        </Sessionprovider>
      </body>
    </html>
  );
}
